packages:
  - apps/*
  - config/*
  - packages/*
catalog:
  "@chromatic-com/storybook": ^3.2.6
  "@fvilers/cls": ^2.0.0
  "@storybook/addon-essentials": ^8.6.14
  "@storybook/blocks": ^8.6.14
  "@storybook/experimental-addon-test": ^8.6.14
  "@storybook/react": ^8.6.14
  "@storybook/react-vite": ^8.6.14
  "@storybook/test": ^8.6.14
  "@types/node": ^22.15.17
  "@vitejs/plugin-react": ^4.4.1
  "@vitejs/plugin-react-swc": ^3.8.0
  "@vitest/browser": ^3.1.4
  "@vitest/coverage-v8": ^3.1.4
  eslint-plugin-storybook: ^0.12.0
  husky: ^9.1.7
  playwright: ^1.52.0
  prettier: ^3.5.3
  react-aria-components: ^1.9.0
  storybook: ^8.6.14
  typescript-plugin-css-modules: ^5.1.0
  vite-bundle-visualizer: ^1.2.1
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.4
